kind: pipeline
name: default

platform:
  arch: amd64

steps:
  - name: lint
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go get -u golang.org/x/lint/golint
      - golint

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag

volumes:
  - name: deps
    temp: {}